<?php

/** @var \Mypage\Second\Block\Display $block */
// [r
?>
<h2>Under text</h2>
<pre>
    <?php
        $block->getHuman();
        var_dump($_REQUEST);
    ?>
    <hr>
    <?php foreach ($block->arr as $k => $v): ?>
        <p><b>ID: <?=$k?></b></p>
        <?php foreach ($v as $key => $value): ?>
        <?=$key?> -> <?=$value?><br>
        <?php endforeach;?>
    <?php endforeach;?>
</pre>

